---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version|lower|replace('/', '_') }}.yml"
        - "{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower|replace('/', '_') }}.yml"
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_architecture }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars
      skip: true
  tags:
    - facts

- name: Add Disco Ubuntu repository
  apt_repository:
    name: disco
    description: Deb packages repo for containerd
    baseurl: "deb http://ports.ubuntu.com/ubuntu-ports disco universe"
    gpgcheck: no
  when: ansible_distribution == "Ubuntu" and not is_atomic

- name: Copy mounts.conf
  copy:
    src: disco.pref
    dest: /etc/apt/preferences.d/disco.pref
  when: ansible_distribution == "Ubuntu" and not is_atomic

- name: Install containerd packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ containerd_packages }}"

- name: Install cri-o service
  service:
    name: "{{ crio_service }}"
    enabled: yes
    state: restarted
